export const comprobanteMap: { [key: string]: string } = {
  'FA': 'Factura A',
  'FB': 'Factura B',
  'FC': 'Factura C',
  'FE': 'Factura E',
  'RB A': 'Recibo A',
  'RB B': 'Recibo B',
  'RB C': 'Recibo C',
  'RB M': 'Recibo M',
  'N/C A': 'Nota de Crédito A',
  'N/C B': 'Nota de Crédito B',
  'N/C C': 'Nota de Crédito C',
  'N/C E': 'Nota de Crédito E',
  'N/C M': 'Nota de Crédito M',
  'N/D A': 'Nota de Débito A',
  'N/D B': 'Nota de Débito B',
  'N/D C': 'Nota de Débito C',
  'N/D E': 'Nota de Débito E',
  'N/D M': 'Nota de Débito M',
  'Mov. Cli.': 'Ajuste manual de cliente',
  'Mov. Prov.': 'Ajuste de proveedor',
  'MOV. STOCK': 'Movimiento de stock',
  'R': 'Remito',
  'Guia': 'Guía de Venta',
  'OP': 'Orden de pago',
  'FM': 'Factura M',
  'DE': 'Despacho de importación'
};
